# Generated by Django 3.2.6 on 2021-08-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0002_auto_20210812_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attandance',
            name='is_active',
        ),
    ]
