# Generated by Django 3.2.6 on 2021-08-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0003_remove_attandance_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='attandance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
