# Generated by Django 3.2.6 on 2021-08-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
